#      ___                            _    ___        _
#    / __> _ _  ___  ___  ___  _ _ _| |_ | . > ___ _| |_
#     \__ \| | || . \| . \/ . \| '_> | |  | . \/ . \ | |
#     <___/`___||  _/|  _/\___/|_|   |_|  |___/\___/ |_|
#                |_|  |_|
#
#           SupportBot created by Emerald Services
#           Installed with MIT License
#

# -------------------------------
#   Command Name Configuration
# -------------------------------

Blacklist: "blacklist"
TicketAdd: "add"
TicketRemove: "remove"
OpenTicket: "ticket"
CloseTicket: "close"
InfoCommand: "ip"
PingCommand: "ping"
HelpCommand: "help"
EmbedCommand: "embed"
SuggestCommand: "suggest"
TranslateCommand: "translate"
UserInfoCommand: "userinfo"

# ---------------------------------------
#   Command Description Configuration
# ---------------------------------------

BlacklistDesc: "Poner a un usuario en la lista negra para que no pueda crear Tickets."
TicketAddDesc: "A침adir un usuario a un ticket de soporte."
TicketRemoveDesc: "Eliminar a un usuario de un ticket de soporte."
TranslateCommandDesc: "Traduce el idioma proporcionado, junto con la abreviatura (2 caracteres) c칩digo largo del idioma"
OpenTicketDesc: "Abrir un nuevo ticket de soporte."
CloseTicketDesc: "Cierra tu ticket de soporte."
InfoCommandDesc: "La informacion del servidor"
PingCommandDesc: "Pong!"
HelpCommandDesc: "Obtener una lista de todos los comandos."
EmbedCommandDesc: "Enviar un mensaje como Embed."
SuggestCommandDesc: "Sugerir una funci칩n para el servidor."
UserInfoCommandDesc: "Obtener informaci칩n sobre un usuario."
