#      ___                            _    ___        _
#    / __> _ _  ___  ___  ___  _ _ _| |_ | . > ___ _| |_
#     \__ \| | || . \| . \/ . \| '_> | |  | . \/ . \ | |
#     <___/`___||  _/|  _/\___/|_|   |_|  |___/\___/ |_|
#                |_|  |_|
#
#           SupportBot created by Emerald Services
#           Installed with MIT License
#
#           Discord Support: https://emeraldsrv.dev/discord
#           Community Resources: https://emeraldsrv.dev/resources

SupportBot_Version: "v7.7.3"

# -------------------------
#   General Configuration
# -------------------------

Name: "LunaMc Bot"
Token: ""

# -------------------------
#  Activity Configuration
# -------------------------

BotActivity: "play.lunamc.us"

StreamingURL: "https://www.twitch.tv/YOUR_TWITCH_NAME"
# Set The ActivityType to "STREAMING" for a streaming status!

ActivityType: "PLAYING"
# Activity status can either be PLAYING, WATCHING, LISTENING or STREAMING.

# -------------------------
#  Embed Configuration
# -------------------------

EmbedColour: "#AB30DA"
EmbedFooter: "LunaMc Bot | Desarrollado por not_staff"

ErrorColour: "#d12519"
SuccessColour: "#04b545"
WarningColour: "#fca117"

# -------------------------
#  Role Configuration
# -------------------------

AutoRole: false
JoinRole: "SupportBot Member"

Staff: "SupportBot Staff"
Admin: "SupportBot Admin"
TicketBlackListRole: "Blacklisted"

# ----------------------------
#  Join/Leave Configuration
# ----------------------------

Welcome: false
  # set to false to disable joining logs

WelcomeChannel: "👋┃lobby"
WelcomeColour: "#f74343"
WelcomeTitle: "User Joined!"
WelcomeMessage: "%joined_user% has joined the server!"
  # Available Placeholders:
  # %joined_user% - Mentions the user who joined

EmbedWelcomeImage: true
EmbedWelcomeImageURL: "https://media.discordapp.net/attachments/958247876344025108/986777740738986094/unknown.png"

EmbedWelcomeThumbnail: "BOT" 
  # "USER" will display the user's profile picture.
  # "BOT" will display the bot's profile picture.
  # false to disable

Leave: false
  # set to false to disable leaving logs

LeaveChannel: "👋┃lobby"
LeaveColour: "#f74343"
LeaveTitle: "User Left!"
LeaveMessage: "%joined_user% has left the server!"
  # Available Placeholders:
  # %joined_user% - Mentions the user who joined

EmbedLeaveImage: true
EmbedLeaveImageURL: "https://cdn.discordapp.com/attachments/958247876344025108/986778170223120384/unknown.png"

EmbedLeaveThumbnail: false 
  # "USER" will display the user's profile picture.
  # "BOT" will display the bot's profile picture.
  # false to disable

# -------------------------
#  Information Configuration
# -------------------------

InfoTitle: "LUNAMC NETWORK 🌙 "

InfoButtonText: "Tienda"
AboutMe: "- ) Seguidamente observaras la información de nuestra network para poder ingresar con exíto, podras ingresar seguidamente por estas direcciónes:\n\n💻 | play.lunamc.us\n🛒 | lunamc.tebex.io\n🎮 | 1.8 - 1.20.x\n\n¡Disfruta de tú estancia por LunaMC Network! 🌙 "
InfoURL: "https://lunamc.tebex.io/"
InfoColour: "#AB30DA"

# ----------------------------
#  Suggestions Configuration
# ----------------------------

SuggestionChannel: "sugerencias-uwu"
SuggestionUpvote: "✅"
SuggestionDownvote: "❌"

SuggestionThreads: true
# set to false to disable threads being created from suggestions.

DisableSuggestions: false
# Set to true to disable the suggestions feature.

# -------------------------
#  Translate Configuration
# -------------------------

TranslateLogChannel: "📚┃logs-only"

# -------------------------
#  Tickets Configuration
# -------------------------

TicketPrefix: "ticket-" # The prefix for ticket channel names

TicketLog: "ticket-data"
TranscriptLog: "ticket-data"

DMTranscripts: true
TranscriptTitle: "Ticket Transcript"
TicketLog_Title: "Ticket Closed"
TicketBlackListMessage: "You are not allowed to open a ticket"
TicketRoleMention: "@here"
TicketClaimMessage: "Your ticket will be handled by" #Automaticly tags user to the end
TicketClaimTitle: "Ticket Claimed"
TicketUnclaimMessage: "Your ticket is now unclaimed by" #Automaticly tags user to the end
TicketUnclaimTitle: "Ticket Unclaimed"
# To ping a role: <@ROLE_ID>

MaxAllowedTickets: 2

TicketSubject: "description"
# "description" will display the ticket reason within the channel description
# "embed" will display the ticket reason within the ticket embed

AllowTicketMentions: true
# Set to true to allow the ticket to mention the author and the support team.
# Set false to dis-allow mentions within tickets.

AllowThanksForReachingOutMessage: true 
# Set to true to allow the "Thanks for reaching out Message" to be sent when the ticket is created
DisableTicketLogChannel: false
# Set to true to disable the requirement of the "TicketLog"
# Set to true to also disable the ticket logs to be sent in the "TicketLogs" channel

# --- Creation Config ---
#      --- Start ---

# Available Placeholders:

# %ticketusername% - User who created the ticket.
# <@%ticketauthor%> - Tags the user who created the ticket.
# <#%ticketid%> - Mentions the ticket channel.

Ticket_Title: "Server Support | %ticketusername%"
TicketMessage: "Hello <@%ticketauthor%>, Thank you for creating a support ticket\nPlease wait patiently whilst a member of our team reaches out to you."

Ticket_Thumbnail: "https://images.emojiterra.com/google/android-pie/512px/1f39f.png"
NoTicketSubject: "No Reason Provided!"

TicketCreatedAlert: ":ticket: Your support ticket has been created: <#%ticketid%>"

AddedUser: "👍 <@%user%> has been added to this ticket"
RemovedUser: "👍 <@%user%> has been removed from this ticket"

# -------------------------
#   Tickets Categories
# -------------------------

Timeout: 5

# Set to true to allow all staff to access the ticket
AllowAllStaff: false

# Ticket roles are the roles that will be able to gain access to tickets depending on what department has been chosen.

Departments:
  - title: "Support"
    role: "SupportBot Staff"
    color: "SECONDARY"
    emoji: "1️⃣"
    category: "Tickets"

  - title: "Billing Support"
    role: "SupportBot Staff"
    color: "SECONDARY"
    emoji: "2️⃣"
    category: "Tickets"

  - title: "Admin Team"
    role: "SupportBot Admin"
    color: "SECONDARY"
    emoji: "3️⃣"
    category: "Tickets"

#  - title: "Other"
#    role: "Staff"
#    color: "SECONDARY"
#    emoji: "3️⃣"
#    category: "Tickets"

# Discord Button Colour Selection
# PRIMARY - Blurple
# SECONDARY - Grey
# DANGER - Red
# SUCCESS - Green

# --- Buttons Config ---
#      --- Start ---

LockTicketCategory: "Archive"
UnlockTicketCategory: "Tickets" #This moves the ticket back to the main category.

TicketCloseEmoji: "❌"
TicketDeleteEmoji: "⛔"
TicketLockEmoji: "🔒"
TicketClaimEmoji: "🧑‍💻"
TicketUnlockEmoji: "🔓"
TicketUnclaimEmoji: "🧑‍💻"

TicketCloseColour: "DANGER"
TicketDeleteColour: "DANGER"
TicketLockColour: "PRIMARY"
TicketClaimColour: "SUCCESS"
TicketUnclaimColour: "DANGER"
TicketUnlockColour: "SUCCES"

# Discord Button Colour Selection
# PRIMARY - Blue
# SECONDARY - Grey
# DANGER - Red
# SUCCESS - Green

TranscriptSavedMessage: "📝 **Transcript Saved!**"
TicketLockMessage: "❌ **Ticket Locked!**"
TicketDeleteMessage: "⚠ **Ticket Deleting!**" # Tickets deleting after 5 seconds by default.

# --- Closing Config ---
#    --- Start ---

StaffOnly: true
ClosingTicket: ":warning: You have requested to close your support ticket."
ClosingConfirmation_Word: "confirm"
CloseConfirmation: true

# ---------------------------
#  Error / Warning Messages
# ---------------------------

IncorrectPerms: ":x: **Err!** No tienes permisos para usar ese comando."
InvalidChannel: ":x: **Err!** Canal no encontrado. Por favor, créelo!"
UserNotFound: ":x: **Err!** Este usuario no existe, ¿Está en este servidor?"
NoValidTicket: ":warning: No puede ejecutar este comando aquí."
TicketExists: ":warning: Este ticket no puede abrirse, ¡ya existe!"
